const ActionTypes = {}

//for login
export const LOGIN_WATCHER = 'LOGIN_WATCHER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const USERPASSWORD_CHANGED = 'USERPASSWORD_CHANGED'
export const USEREMAIL_CHANGED = 'USEREMAIL_CHANGED'
export const USERTOKEN_CHANGED = 'USERTOKEN_CHANGED'

export const SAVE_LOGIN_DATA = 'SAVE_LOGIN_DATA'
export const SAVE_LOGIN_USER_PROFILE_DATA = 'SAVE_LOGIN_USER_PROFILE_DATA'
export const GET_LOGIN_DATA = 'GET_LOGIN_DATA'

//for edit person info
export const UPDATE_INPUT_FIELDS = 'UPDATE_INPUT_FIELDS'
export const UPDATE_USER_TYPE = 'UPDATE_USER_TYPE'
export const UPDATE_ERROR_ALERT = 'UPDATE_ERROR_ALERT'
export const GET_PROFILE_DETAILS = 'GET_PROFILE_DETAILS'
export const GET_PROFILE_DETAILS_SUCCESS = 'GET_PROFILE_DETAILS_SUCCESS'
export const GET_PROFILE_DETAILS_FAIL = 'GET_PROFILE_DETAILS_FAIL'
export const UPDATE_PROFILE_DETAILS = 'UPDATE_PROFILE_DETAILS'
export const UPDATE_PROFILE_DETAILS_SUCCESS = 'UPDATE_PROFILE_DETAILS_SUCCESS'
export const UPDATE_PROFILE_DETAILS_FAIL = 'UPDATE_PROFILE_DETAILS_FAIL'

export default ActionTypes
