import {StyleSheet, Dimensions} from 'react-native';
import {Matrics, Fonts, Color} from '../../common/styles';

const styles = StyleSheet.create({
  mainContainer: {
    paddingTop: Matrics.ScaleValue(20),
    backgroundColor: Color.white,
    width: '100%',
  },
  step2BodyContainer: {flex: 1, marginHorizontal: Matrics.ScaleValue(20)},
  citizenBtn: {
    minWidth: '80%',
    paddingVertical: Matrics.ScaleValue(10),
    paddingHorizontal: Matrics.ScaleValue(20),
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Color.btnLightBorder,
    marginTop: Matrics.ScaleValue(20),
    alignItems: 'center',
    backgroundColor: Color.white,
  },
  contentTitle: {
    fontFamily: Fonts.type.OpenSansBold,
    fontSize: Matrics.ScaleValue(18),
    color: Color.charcoalGrey,
    alignSelf: 'center',
  },
  stylesCitizenBtnText: {
    fontFamily: Fonts.type.OpenSansMedium,
    fontSize: Matrics.ScaleValue(18),
    color: Color.charcoalGrey,
  },
  nricImageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginVertical: Matrics.ScaleValue(20),
  },
  nricUploadBtn: {
    height: 120,
    width: 120,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Color.btnLightGreyBg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Color.btnLightBorder,
    marginHorizontal: Matrics.ScaleValue(15),
  },
  docUploadBtn: {
    height: 120,
    width: 120,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Color.btnLightGreyBg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Color.btnLightBorder,
    margin: Matrics.ScaleValue(15),
    alignSelf: 'center',
  },
  uploadImageLabel: {
    textAlign: 'center',
    marginTop: Matrics.ScaleValue(10),
    fontSize: Matrics.ScaleValue(16),
  },
  termsText: {
    fontSize: Matrics.ScaleValue(14),
    lineHeight: Matrics.ScaleValue(18),
    flex: 1,
    marginLeft: Matrics.ScaleValue(5),
    fontFamily: Fonts.type.OpenSansMedium,
  },
  termsContainer: {
    marginTop: Matrics.ScaleValue(20),
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: Matrics.ScaleValue(15),
  },

  submitBtn: {
    marginVertical: Matrics.ScaleValue(20),
    backgroundColor: Color.blue,
    marginHorizontal: Matrics.ScaleValue(15),
    width: Matrics.screenWidth - Matrics.ScaleValue(30),
    borderWidth: 1,
    borderRadius: Matrics.ScaleValue(10),
    borderColor: Color.blue,
  },
  submitBtnText: {
    fontSize: Matrics.ScaleValue(16),
    lineHeight: Matrics.ScaleValue(20),
    padding: Matrics.ScaleValue(10),
    fontFamily: Fonts.type.OpenSansBold,
    textAlign: 'center',
    color: Color.white,
  },
  root: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    backgroundColor: '#FFF',
    paddingBottom: Matrics.ScaleValue(20),
    flexGrow: 1,
  },
  greenTickBigIcon: {
    height: 100,
    width: 100,
    marginVertical: Matrics.ScaleValue(20),
    alignSelf: 'center',
  },
  stepsTitleText: {
    fontSize: Matrics.ScaleValue(18),
    lineHeight: Matrics.ScaleValue(28),
    padding: Matrics.ScaleValue(10),
    fontFamily: Fonts.type.OpenSansBold,
    marginTop: Matrics.ScaleValue(20),
    width: '100%',
    color: Color.darkBtnBlack,
  },
  optionRowIconView: {
    width: 40,
    marginLeft: 10,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
  },
  pointsText: {
    fontSize: Matrics.ScaleValue(16),
    lineHeight: Matrics.ScaleValue(20),
    fontFamily: Fonts.type.OpenSans,
    marginTop: Matrics.ScaleValue(20),
  },
  professionIconContainer: {
    height: 80,
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },
  professionIconBtn: {
    width: 80,
  },
  professionRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    marginVertical: Matrics.ScaleValue(20),
  },
  professionText: {
    fontSize: Matrics.ScaleValue(14),
    lineHeight: Matrics.ScaleValue(20),
    fontFamily: Fonts.type.OpenSansMedium,
    marginTop: Matrics.ScaleValue(10),
    textAlign: 'center',
    color: Color.darkBtnBlack,
  },
  reqDocContainer: {
    margin: Matrics.ScaleValue(15),
  },
  orderedRow: {
    flexDirection: 'row',
  },
  srNo: {
    width: 20,
    fontSize: Matrics.ScaleValue(16),
    lineHeight: Matrics.ScaleValue(30),
    fontFamily: Fonts.type.OpenSansBold,
    color: Color.black,
  },
  srData: {
    fontSize: Matrics.ScaleValue(16),
    lineHeight: Matrics.ScaleValue(30),
    fontFamily: Fonts.type.OpenSans,
    flex: 1,
    color: Color.black,
  },
  srTitle: {
    fontSize: Matrics.ScaleValue(16),
    lineHeight: Matrics.ScaleValue(30),
    fontFamily: Fonts.type.OpenSansBold,
    color: Color.black,
  },
  uploadSubTitle: {
    fontSize: Matrics.ScaleValue(14),
    lineHeight: Matrics.ScaleValue(20),
    fontFamily: Fonts.type.OpenSans,
    color: Color.darkBtnBlack,
    marginBottom: Matrics.ScaleValue(15),
    alignSelf: 'center',
  },
  uploadTitle: {
    fontSize: Matrics.ScaleValue(16),
    lineHeight: Matrics.ScaleValue(20),
    fontFamily: Fonts.type.OpenSansBold,
    color: Color.black,
    alignSelf: 'center',
  },
  uploadFilesContainer: {
    margin: Matrics.ScaleValue(15),
  },
  imagePrevRow: {
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'center',
  },
  uploadedImgStyle: {
    height: 25,
    width: 25,
    marginHorizontal: 10,
    borderRadius: 13,
  },
  uploadImageName: {
    fontSize: Matrics.ScaleValue(14),
    lineHeight: Matrics.ScaleValue(20),
    fontFamily: Fonts.type.OpenSans,
    flex: 1,
    color: Color.black,
  },
  uploadMoreText: {
    fontSize: Matrics.ScaleValue(16),
    lineHeight: Matrics.ScaleValue(30),
    fontFamily: Fonts.type.OpenSansMedium,
    color: Color.contentText,
  },
  uploadDeleteIcon: {
    // marginRight: 5,
  },
  uploadGreenTick: {
    marginRight: 10,
  },
  upload_more: {
    marginRight: 5,
  },
  uploadProfessionRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginBottom: Matrics.ScaleValue(25),
  },
  professionBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    width: 130,
    flexDirection: 'row',
    backgroundColor: Color.bubbleLightGray,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Color.darkBtnBlack,
    borderRadius: 10,
  },
});

export default styles;
